import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navigation } from "./components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>ForoARdev</title>
      </head>
      <body className="flex flex-col bg-gray-800">
        <Navigation />
        <div className="flex-grow h-auto">{children}</div>
      </body>
    </html>
  );
}
